### ISSUE TITLE
when enter gmail/ mail id  for forgot pin click send button app crash .

### ISSUE THREAD

**Issue by ayushimundra30** [ankitverma31/AntiTheftAlarm#1]
**Error : 09-03 13:36:07.582 22348-23293/seproject.antitheftalarm E/dalvikvm: Could not find class 'com.sun.mail.util.MailLogger', referenced from method javax.mail.Session.initLogger
09-03 13:36:07.772 22348-23293/seproject.antitheftalarm E/dalvikvm: Could not find class 'com.sun.mail.util.LineInputStream', referenced from method javax.mail.Session.loadProvidersFromStream**
09-03 13:36:07.852 22348-23293/seproject.antitheftalarm E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                          Process: seproject.antitheftalarm, PID: 22348
                                                                          java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at **java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                           Caused by: java.lang.NoClassDefFoundError: com.sun.mail.util.MailLogger
                                                                              at javax.mail.Session.initLogger(Session.java:226)
                                                                              at javax.mail.Session.<init>(Session.java:210)
                                                                              at javax.mail.Session.getInstance(Session.java:247)
                                                                              at seproject.antitheftalarm.SendMail.doInBackground(SendMail.java:76)
                                                                              at seproject.antitheftalarm.SendMail.doInBackground(SendMail.java:24)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                              at java.lang.Thread.run(Thread.java:841)** 
09-03 13:36:08.733 22348-22348/seproject.antitheftalarm E/WindowManager: android.view.WindowLeaked: Activity seproject.antitheftalarm.ForgotPin has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41e5c558 V.E..... R......D 0,0-580,163} that was originally added here
                                                                             at android.view.ViewRootImpl.<init>(ViewRootImpl.java:463)
                                                                             at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:267)
                                                                             at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                             at android.app.Dialog.show(Dialog.java:289)
                                                                             at android.app.ProgressDialog.show(ProgressDialog.java:117)
                                                                             at android.app.ProgressDialog.show(ProgressDialog.java:105)
                                                                             at seproject.antitheftalarm.SendMail.onPreExecute(SendMail.java:51)
                                                                             at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
                                                                             at android.os.AsyncTask.execute(AsyncTask.java:535)
                                                                             at seproject.antitheftalarm.ForgotPin.sendEmail(ForgotPin.java:46)
                                                                             at seproject.antitheftalarm.ForgotPin.onClick(ForgotPin.java:78)
                                                                             at android.view.View.performClick(View.java:4633)
                                                                             at android.view.View$PerformClick.run(View.java:19280)
                                                                             at android.os.Handler.handleCallback(Handler.java:733)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5598)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                             at dalvik.system.NativeStart.main(Native Method)
09-03 13:41:08.305 27618-27618/seproject.antitheftalarm E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: onDecode : QmageDecodeFrame 20140421 Rev.6376 
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: This is decoding
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: decoding stream->hasLength()
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: onDecode : QmageDecParseHeader call : QM
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: Qmage parsing for decoding ok
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: onDecode :  QmageHeader.NinePatched 0
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: onDecode : QmageHeader Height() 38 Width() : 70 sampleSize : 1
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: Qmage Make Color table
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: SkBitmap::kIndex8_Config == config && 1 == sampleSize
09-03 13:41:08.315 27618-27618/seproject.antitheftalarm E/Qmage: onDecode : return true QM
09-03 13:41:08.335 27618-27618/seproject.antitheftalarm E/Qmage: onDecode : QmageDecodeFrame 20140421 Rev.6376 
09-03 13:41:08.335 27618-27618/seproject.antitheftalarm E/Qmage: This is decoding
09-03 13:41:08.335 27618-27618/seproject.antitheftalarm E/Qmage: decoding stream->hasLength()
09-03 13:41:08.335 27618-27618/seproject.antitheftalarm E/Qmage: onDecode : QmageDecParseHeader call : QM
09-03 13:41:08.335 27618-27618/seproject.antitheftalarm E/Qmage: Qmage parsing for decoding ok
09-03 13:41:08.335 27618-27618/seproject.antitheftalarm E/Qmage: onDecode :  QmageHeader.NinePatched 0

see the Bold part . App crashes . Can u please help me out . To resolve this issue .

**Comment by ankitverma31** [comment]
Hi aniayu,
Did you add **jar files** required to send mail in libs folder? for more details check this out [Sending Mail in android](https://www.simplifiedcoding.net/android-email-app-using-javamail-api-in-android-studio/)

**Comment by ayushimundra30** [comment]
I added the jar files manually downloaded from java.jar . files because in
ur code jar files are not present . If jar files of specific version we
need to add can you please send it me .

**Comment by ankitverma31** [comment]
Download those 3 jar files required to send mail from [here](https://drive.google.com/open?id=0B6nsuDs648BgWDByZVpKQk9YM0k) and put it in your app->libs folder. Let me know if you still face any problem.

**Comment by ayushimundra30** [comment]
Hi ,
I am still phasing the same issue .
compile files('libs/activation.jar')
compile files('libs/additionnal.jar')
compile files('libs/mail.jar')
Added three dependancy in androi app graadle as file dependancy . still Its
crashing from me .

**Comment by ayushimundra30** [comment]
Did u check that issue ? 

Regards
Ayushi Mundra

**Comment by ankitverma31** [comment]
Hey Ayushi,
I have updated the repo so download again and try now. And let me know if it's working or not.

**Comment by ayushimundra30** [comment]
Hi ,

U have edited EnterPin.java and config File . But the error which is coming
in sendMail.java file How come this resolb=ve is issue . In config.java I
already modified with changes you mentioned .i will check n update you .
